name: Build Python Game

on:
  push:
  workflow_dispatch:

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name SuperMarioPython main.py

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: SuperMarioPython-Windows
          path: dist/*

  build-macos:
    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller

      - name: Build APP
        run: |
          pyinstaller --windowed --name SuperMarioPython main.py

      - name: Create DMG
        run: |
          mkdir dmg
          cp -R dist/SuperMarioPython.app dmg/
          hdiutil create -volname "SuperMarioPython" -srcfolder dmg -ov -format UDZO SuperMarioPython.dmg

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: SuperMarioPython-macOS
          path: |
            dist/*.app
            *.dmg
